---
- name: Retrieve VMware Information
  hosts: localhost
  gather_facts: false
  collections:
    - cloud.vmware_ops
  vars:
    vcenter_hostname: "192.168.51.100"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "P@ssw0rd.1"
    vm_name: "rhel8-test"  # Change to the VM you want to query

  tasks:
    - name: Gather information about a specific VM
      cloud.vmware_ops.info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        vm_name: "{{ vm_name }}"
        validate_certs: false  # Set to true if you are using valid SSL certificates
      register: vm_info

    - name: Display gathered information
      debug:
        var: vm_info
