---
- name: Verify SSH Configuration
  hosts: all
  become: yes
  tasks:
    - name: Check if SSH service is running
      service:
        name: ssh
        state: started
      register: ssh_service_status

    - name: Verify SSH service status
      debug:
        msg: "SSH service is {{ ssh_service_status.state }}."

    - name: Check SSH configuration file for syntax errors
      command: sshd -t
      register: sshd_syntax_check
      failed_when: sshd_syntax_check.rc != 0

    - name: Show SSH configuration file validation result
      debug:
        var: sshd_syntax_check

    - name: Check if SSH port is listening
      command: netstat -tuln | grep ":22"
      register: ssh_port_check
      failed_when: ssh_port_check.rc != 0

    - name: Display SSH port listening check result
      debug:
        var: ssh_port_check.stdout_lines