---
- hosts: all

  vars:
    oscap_profile: ospp
    oscap_policy: ssg-rhel8-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      ansible.builtin.command: oscap xccdf eval \ 
        --profile {{ oscap_profile }} \ 
        --results /tmp/oscap-arf.xml \ 
        --report /tmp/oscap-report.html \ 
        --fetch-remote-resources \ 
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml
      ignore_errors: true
      register: scap_cmd 

    - name: generate playbook openscap
      ansible.builtin.command: oscap xccdf generate fix \
        --fix-type ansible \
        --result-id "" /tmp/oscap-arf.xml \
        --output /tmp/oscap-remediation.yml
      ignore_errors: true
      register: rem_cmd
      when:
        - remediate is defined
        - remediate|bool
    
    - name: Check for failure and escalate unless specified otherwise
      ansible.builtin.fail:
        msg: Security scan failed
      when: 
        - scap_cmd.rc | int != 0
        - ((ignore_errors is defined and not ignore_errors|bool) or (ignore_errors is not defined))
        - (remediate is not defined or not remediate|bool)

    always:
    - name: download report
      fetch:
        src: /tmp/oscap-report.html
        dest: /oscap-reports/{{ inventory_hostname }}.html
        flat: yes