---
- name: Transfer file backup dari VM 1 ke VM 2
  hosts: restore
  become: true
  vars:
    dest_host: "192.168.51.21"
    source_path: "/var/backups/"
    dest_path: "/restore/"
  tasks:
    - name: Push directory to remote destination
      ansible.posix.synchronize:
        src: "{{ source_path }}"
        dest: "{{ dest_host }}:{{ dest_path }}"
        mode: push
        archive: true
