---
- name: Push /var/backups from 192.168.30.17 to 192.168.51.21:/restore
  hosts: backup
  become: true
  vars:
    dest_host: "192.168.51.21"
    source_path: "/var/backups/"
    dest_path: "/restore/"
  tasks:
    - name: Rsync push to destination host
      ansible.posix.synchronize:
        src: "{{ source_path }}"
        dest: "{{ dest_host }}:{{ dest_path }}"
        mode: pull
        rsync_path: "rsync"
        archive: true
      delegate_to: "{{ source_host }}"
