# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get Windows VM VBS enablement status
- name: "Initialize VM VBS enablement status"
  set_fact:
    vm_vbs_enabled: false

- name: "Get VM VBS enablement status"
  include_tasks: vm_get_config.yml
  vars:
    property_list: ['config.flags.vbsEnabled']

- name: "Set fact of VM VBS enablement status"
  ansible.builtin.set_fact:
    vm_vbs_enabled: "{{ vm_config.config.flags.vbsEnabled | bool }}"
  when:
    - vm_config.config is defined
    - vm_config.config.flags is defined
    - vm_config.config.flags.vbsEnabled is defined

- name: "Display VM VBS enablement status"
  ansible.builtin.debug: var=vm_vbs_enabled
