---
- name: Gather information from VMs
  hosts: all
  gather_facts: yes  # Automatically gather basic facts (OS, IP, etc.)
  tasks:
    - name: Gather detailed information about the system
      setup:
        gather_subset:
          - all  # You can specify certain subsets like 'hardware', 'network', 'virtual', etc.
      register: vm_facts

    - name: Display gathered information
      debug:
        var: vm_facts
