---
- name: List all VMs in a VMware environment
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: no  # Set to 'yes' if using trusted certs

  tasks:
    - name: Gather information about all VMs
      community.vmware.vmware_guest_facts:
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Display list of all VMs
      debug:
        var: vm_info
