---
- name: Check for expired users on Windows
  hosts: windows
  tasks:
    - name: Get details of all local users
      win_shell: |
        Get-LocalUser | Select-Object Name,Enabled,PasswordExpired
      register: local_users

    - name: Display users whose passwords have expired or accounts are disabled
      debug:
        msg: "{{ item.Name }} - Enabled: {{ item.Enabled }}, Password Expired: {{ item.PasswordExpired }}"
      loop: "{{ local_users.stdout_lines | from_json }}"
      when: item.PasswordExpired -eq $true or item.Enabled -eq $false